import Head from "next/head";
import WeatherApp from "../components/WeatherApp";
import { useState } from "react";
import Image from "next/image"

//api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
export default function Home() {
  const [showApp, setShowApp] = useState(false);
  return (
    <div>
      <Head>
        <title>My Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-app.ico" />
      </Head>
      {showApp ? (
        <WeatherApp />
      ) : (
        <div className="App">
          <div className="display my-2">
          <h1 className="display-4 fw-bold mb-4">Welcome</h1>
            <Image src="/icon.png" alt="Icon " width={250} height={250} />
            <div className="my-5">
            <button
              className="btn btn-dark "
              onClick={() => setShowApp(true)}
            >
              View Weather
            </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
